# ═══════════════════════════════════════════════════════════
#   PvP — режим PvP с боссбаром и скорбордом
#   Используйте & для цветовых кодов (например, &c для красного)
#   {time} — оставшееся время
#   {player} — ник игрока
#   {health} — здоровье игрока
# ═══════════════════════════════════════════════════════════

# Защита новичка (нельзя вступать в PvP пока не наиграешь N часов)
newbie-protection:
  enabled: true
  playtime-hours: 2

# Команда при входе в PvP и при выходе из PvP
pvp-command: "/sdfdspvponssdsdf"

# Длительность PvP режима в секундах после удара
combat-duration: 20

# Настройки боссбара
bossbar:
  title: "&c&l⚔ ПВП РЕЖИМ &f{time}"
  color: RED
  style: SOLID

# Настройки скорборда
scoreboard:
  title: "&c&l⚔ ПВП РЕЖИМ"
  lines:
    - "&7▬▬▬▬▬▬▬▬▬▬"
    - "&eНик: &f{player}"
    - "&eHP: &c{health} &c❤"
    - "&7▬▬▬▬▬▬▬▬▬▬"
    - "&eДо конца: &f{time}"
    - "&7▬▬▬▬▬▬▬▬▬▬"
